### ISSUE TITLE
Add line to README.md for building an IOC with pydev support

### ISSUE THREAD

**Issue by gauge2** [klemenv/PyDevice#11]
After failing to make the connection, I realised defining `PYTHON_CONFIG` only in  `PyDevice/configure/CONFIG_SITE` for building the PyDevice module and not for the IOC, adding the lines to the MAKEFILE is not sufficient. 

I propose that we add to the README.md in the section for adding `pydev` support to an IOC:

```
- Edit configure/CONFIG_SITE and add the same 'PYTHON_CONFIG' variable as set in the configure/CONFIG_SITE for the PyDevice build.
```

Adding this variable to the shell at login would kill two birds with one stone but feel that it makes it harder to undetrstand what is going on if one is relatively new to EPICS. 

Let me know if you think it's valid and I can make the pull request if you want.

**Comment by klemenv** [comment]
Makefile needs to call python-config --ldflags to get libraries needed to link against. The test IOC does it like this:

```
PYTHON_EMBED := $(shell $(PYTHON_CONFIG) --help | grep embed)
ifeq ($(PYTHON_EMBED),)
	SYS_PROD_LIBS += $(shell $(PYTHON_CONFIG) --ldflags | sed 's/-[^l][^ ]*//g' | sed 's/-l//g')
else
	SYS_PROD_LIBS += $(shell $(PYTHON_CONFIG) --ldflags --embed | sed 's/-[^l][^ ]*//g' | sed 's/-l//g')
endif
```

This is needed to support either Python2 or Python3, since some version of Python3 started requiring the --embed flag. The README.md should be updated to include this.

In addition, as you suggest, PYTHON_CONFIG would need to be defined. Maybe a more convenient approach would be for PyDevice to provide a configure/CONFIG_SITE.include file with a definition of PYTHON_CONFIG, which the IOC could then include. PyDevice's configure/CONFIG_SITE would also reference the configure/CONFIG_SITE.include
